const F1_TEAMS = [
  { id:'redbull',     name:'Red Bull Racing',    short:'RBR', color1:'#1E1E5E', color2:'#FF2020', speed:98,
    drivers:[{name:'Max Verstappen',num:1},{name:'Sergio Perez',num:11}] },
  { id:'mclaren',     name:'McLaren',             short:'MCL', color1:'#FF8000', color2:'#000000', speed:95,
    drivers:[{name:'Lando Norris',num:4},{name:'Oscar Piastri',num:81}] },
  { id:'ferrari',     name:'Ferrari',             short:'FER', color1:'#DC0000', color2:'#FFFFFF', speed:94,
    drivers:[{name:'Charles Leclerc',num:16},{name:'Carlos Sainz',num:55}] },
  { id:'mercedes',    name:'Mercedes',            short:'MER', color1:'#00D2BE', color2:'#FFFFFF', speed:92,
    drivers:[{name:'Lewis Hamilton',num:44},{name:'George Russell',num:63}] },
  { id:'astonmartin', name:'Aston Martin',        short:'AMR', color1:'#006F62', color2:'#CEDC00', speed:87,
    drivers:[{name:'Fernando Alonso',num:14},{name:'Lance Stroll',num:18}] },
  { id:'alpine',      name:'Alpine',              short:'ALP', color1:'#0090FF', color2:'#FF0087', speed:83,
    drivers:[{name:'Esteban Ocon',num:31},{name:'Pierre Gasly',num:10}] },
  { id:'rb',          name:'RB F1 Team',          short:'RBF', color1:'#1434CB', color2:'#FFFFFF', speed:82,
    drivers:[{name:'Yuki Tsunoda',num:22},{name:'Daniel Ricciardo',num:3}] },
  { id:'williams',    name:'Williams',            short:'WIL', color1:'#005AFF', color2:'#FFFFFF', speed:80,
    drivers:[{name:'Alexander Albon',num:23},{name:'Logan Sargeant',num:2}] },
  { id:'sauber',      name:'Kick Sauber',         short:'SAU', color1:'#00AA00', color2:'#FFFFFF', speed:79,
    drivers:[{name:'Valtteri Bottas',num:77},{name:'Zhou Guanyu',num:24}] },
  { id:'haas',        name:'Haas F1 Team',        short:'HAS', color1:'#AAAAAA', color2:'#E8002D', speed:78,
    drivers:[{name:'Kevin Magnussen',num:20},{name:'Nico Hülkenberg',num:27}] },
];
