const TEAMS = [
  {
    id: 'bayern',
    name: 'Bayern München',
    shortName: 'FCB',
    country: '🇩🇪 Deutschland',
    primaryColor: '#DC052D',
    secondaryColor: '#FFFFFF',
    rating: 90,
    attackRating: 88,
    defenseRating: 85,
    speed: 87
  },
  {
    id: 'dortmund',
    name: 'Borussia Dortmund',
    shortName: 'BVB',
    country: '🇩🇪 Deutschland',
    primaryColor: '#FDE100',
    secondaryColor: '#000000',
    rating: 84,
    attackRating: 85,
    defenseRating: 78,
    speed: 86
  },
  {
    id: 'realmadrid',
    name: 'Real Madrid',
    shortName: 'RMA',
    country: '🇪🇸 Spanien',
    primaryColor: '#FFFFFF',
    secondaryColor: '#002E6D',
    rating: 92,
    attackRating: 91,
    defenseRating: 88,
    speed: 88
  },
  {
    id: 'barcelona',
    name: 'FC Barcelona',
    shortName: 'FCB',
    country: '🇪🇸 Spanien',
    primaryColor: '#A50044',
    secondaryColor: '#004D98',
    rating: 88,
    attackRating: 90,
    defenseRating: 82,
    speed: 89
  },
  {
    id: 'mancity',
    name: 'Manchester City',
    shortName: 'MCI',
    country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
    primaryColor: '#6CABDD',
    secondaryColor: '#1C2C5B',
    rating: 91,
    attackRating: 92,
    defenseRating: 87,
    speed: 87
  },
  {
    id: 'liverpool',
    name: 'Liverpool FC',
    shortName: 'LFC',
    country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
    primaryColor: '#C8102E',
    secondaryColor: '#F6EB61',
    rating: 87,
    attackRating: 88,
    defenseRating: 83,
    speed: 88
  },
  {
    id: 'psg',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    country: '🇫🇷 Frankreich',
    primaryColor: '#004170',
    secondaryColor: '#DA291C',
    rating: 86,
    attackRating: 89,
    defenseRating: 80,
    speed: 87
  },
  {
    id: 'juventus',
    name: 'Juventus FC',
    shortName: 'JUV',
    country: '🇮🇹 Italien',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
    rating: 83,
    attackRating: 82,
    defenseRating: 84,
    speed: 82
  },
  {
    id: 'chelsea',
    name: 'FC Chelsea',
    shortName: 'CHE',
    country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
    primaryColor: '#034694',
    secondaryColor: '#FFFFFF',
    rating: 82,
    attackRating: 81,
    defenseRating: 80,
    speed: 82
  },
  {
    id: 'acmilan',
    name: 'AC Milan',
    shortName: 'ACM',
    country: '🇮🇹 Italien',
    primaryColor: '#FB090B',
    secondaryColor: '#000000',
    rating: 84,
    attackRating: 83,
    defenseRating: 82,
    speed: 83
  },
  {
    id: 'arsenal',
    name: 'FC Arsenal',
    shortName: 'ARS',
    country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
    primaryColor: '#EF0107',
    secondaryColor: '#FFFFFF',
    rating: 84,
    attackRating: 85,
    defenseRating: 80,
    speed: 85
  },
  {
    id: 'atletico',
    name: 'Atlético Madrid',
    shortName: 'ATM',
    country: '🇪🇸 Spanien',
    primaryColor: '#272E61',
    secondaryColor: '#CB3524',
    rating: 83,
    attackRating: 80,
    defenseRating: 87,
    speed: 81
  }
];
